# Default initial positions for ArmURDF2's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  joint_7_1: 0
  joint_7_2: 0
  joint_8_1: 0
  joint_8_2: 0
  joint_9_1: 0
  joint_9_2: 0