#!/bin/bash

# CPRT bash aliases
# firstTimeInstall.sh will handle adding code to bashrc to source this file

cprt_bash_alias_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export BASH_ALIASES_CPRT="$cprt_bash_alias_dir/cprt_bash_aliases"
alias eaCPRT='vim $BASH_ALIASES_CPRT && source ~/.bashrc && echo "CPRT Bash Aliases Updated"'
