/**:
  ros__parameters:
    resize_for_processing: {"HD1080": 0.5, "HD2K": 0.25, "default": 0.5}

    blue_led: "ColourProcessing(
        image_scaling=0.6,
        display_scaling=0.7,
        process_steps=tuple([
            HSVRangeMaskStep('Step 1 - HSV - Blue', HSVRange(HSV(95, 192, 96), HSV(127, 255, 255)), return_mask=True),
            ErodeDilateStep('Step 2 - Erode small bits then Dilate to regroup', erosion=1, dilation=4, erosion_before_dilate=True, return_mask=True),
            FindContours('Step 3 - Find Contours'),
            FilterInnerContours('Step 4 - Reject Inner Contours', reject_inner_contours=True),
            FilterByContourArea('Step 5 - Reject By Area', reject_below=67, far_close_divider=204, reject_above=9919),
        ]))"

    red_led: "ColourProcessing(
        image_scaling=0.6,
        display_scaling=0.7,
        process_steps=tuple([
            HSVRangeMaskStep('Step 1 - HSV - Red', HSVRange(HSV(15, 180, 50), HSV(174, 252, 255)), return_mask=True, invert_hue=True),
            ErodeDilateStep('Step 2 - Erode small bits then Dilate to regroup', erosion=1, dilation=4, erosion_before_dilate=True, return_mask=True),
            FindContours('Step 3 - Find Contours'),
            FilterInnerContours('Step 4 - Reject Inner Contours', reject_inner_contours=True),
            FilterByContourArea('Step 5 - Reject By Area', reject_below=40, far_close_divider=204, reject_above=6785),
        ]))"

    ir_led: ""