zed:
  ros__parameters:
    # openni_depth_mode: Convert 32bit depth in meters to 16bit in millimeters
    openni_depth_mode: false
    depth_image_scaling: 0.4444444444444444 # 4/9
    mask_filename: 'ZEDMask.png'

    zed_arucos_detections: True
    blue_led_detections: False
    red_led_detections: False
    ir_led_detections: True

    ir_undistort_pitch_offset: 0.0
    ir_undistort_pitch_slope: 0.28
    ir_undistort_yaw_offset: -29.0
    ir_undistort_yaw_slope: 0.25

    detect_6x6_aruco_as_leds: True

    publish_raw_image: True
    publish_cv_processed_image: True

    enable_gl_viewer: False

    svo_realtime_mode: False # Doesn't work on Jetson Nano
    always_record: False
    default_record_filename: ''

    resolution: "HD1080" # Options: HD720, HD1080, HD1200, HD2K
    fps: 30
    depth_maximum_distance: 15 # meters
  
    exposure: -1
    gain: -1
    gamma: -1
    white_balance: -1

    enable_object_tracking: True
