zed:
  ros__parameters:
    zed_arucos_detections: True
    blue_led_detections: True
    red_led_detections: True
    ir_led_detections: True

    detect_6x6_aruco_as_leds: False

    publish_raw_image: True
    publish_cv_processed_image: True

    enable_gl_viewer: False

    svo_realtime_mode: False # Doesn't work on Jetson Nano
    always_record: False
    default_record_filename: ''

    resolution: "HD1080" # Options: HD720, HD1080, HD1200, HD2K
    fps: 30
    depth_maximum_distance: 15 # meters
  
    exposure: 50
    gain: 95
    gamma: 7
    white_balance: 4600

    enable_object_tracking: False