zed_node:
  ros__parameters:
    publish_cv_processed_image: True

    svo_realtime_mode: False # Doesn't work on Jetson Nano
    always_record: False
    default_record_filename: ''

    resolution: "HD1080" # Options: HD720, HD1080, HD1200, HD2K
    fps: 30
    depth_maximum_distance: 15 # meters

    exposure: 50
    gain: 95
    gamma: 7

    enable_object_tracking: False