ublox_gps_node:
  ros__parameters:
    debug: 1 # Range 0-4 (0 means no debug statements will print)
    device: /dev/xxxx # To be changed to cooresponding device
    frame_id: gps
    config_on_startup: false # Loads config from flash memory
    uart1:
      baudrate: 115250

    publish:
      all: true # Publishing all messages
